// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace eftpt.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20230511004540_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0-preview.3.23174.2");

            modelBuilder.Entity("User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Employee", b =>
                {
                    b.HasBaseType("User");

                    b.Property<int>("Salary")
                        .HasColumnType("INTEGER");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Manager", b =>
                {
                    b.HasBaseType("User");

                    b.Property<string>("Departament")
                        .HasColumnType("TEXT");

                    b.ToTable("Managers");
                });

            modelBuilder.Entity("Employee", b =>
                {
                    b.HasOne("User", null)
                        .WithOne()
                        .HasForeignKey("Employee", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Manager", b =>
                {
                    b.HasOne("User", null)
                        .WithOne()
                        .HasForeignKey("Manager", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
