// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace efhierarchy.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20230510083520_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0-preview.3.23174.2");

            modelBuilder.Entity("Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER")
                        .HasColumnName("category");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<int?>("MasterId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("master_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_tags");

                    b.HasIndex("MasterId")
                        .HasDatabaseName("ix_tags_master_id");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("Tag", b =>
                {
                    b.HasOne("Tag", "Master")
                        .WithMany("Slaves")
                        .HasForeignKey("MasterId")
                        .HasConstraintName("fk_tags_tags_master_id");

                    b.Navigation("Master");
                });

            modelBuilder.Entity("Tag", b =>
                {
                    b.Navigation("Slaves");
                });
#pragma warning restore 612, 618
        }
    }
}
